export const TEXT = {
  en: {
    appTitle: "Triseal",
    subtitle: "Chart a living sea. Leave no thread behind.",
    homeEyebrow: "A CARD ROGUELITE BENEATH THE SURFACE",
    homeDescription: "The drowned observatory has lost its horizon. Read the currents, weave a way through, and bring a little light back to the archive.",
    begin: "Begin a chart",
    continueRun: "Continue expedition",
    seedLabel: "Run seed",
    seedPlaceholder: "Random if left blank",
    seedHint: "Share a seed to replay the same route.",
    welcome: "Three currents. One wake.",
    welcomeDescription: "Choose a reaction with your first two different sigils, then play the third to unleash a Wake.",
    howTo: "How to play",
    language: "中文",
    sound: "Sound",
    settings: "Settings",
    settingsTitle: "Chart settings",
    close: "Close",
    soundToggle: "Sound effects and music",
    reducedMotion: "Reduce motion",
    volume: "Master volume",
    musicToggle: "Ambient score",
    on: "On",
    off: "Off",
    helpTitle: "A chart in three currents",
    helpWakeTitle: "Shape a Resonance",
    helpWakeBody: "Your first two different sigils choose a Resonance: Tide + Ember makes Steam (foe attacks −2 this turn); Ember + Glass makes Prism (your next attack gains +3 damage per foe hit); Glass + Tide makes Mirror (gain 5 guard). Add the third sigil for a Wake: deal 4 to all foes, gain 4 guard, and draw 1. Repeats do not change the pair.",
    helpTurnTitle: "Read the water",
    helpTurnBody: "Each foe shows its next move before you act. Spend 3 energy, play cards in any order, then end your turn. Guard absorbs damage until the turn ends.",
    helpReweaveTitle: "Reweave once",
    helpReweaveBody: "Once per expedition, replace your current hand with the same number of cards. Use it before ending a difficult turn.",
    helpRouteTitle: "Choose your passage",
    helpRouteBody: "After the first encounter, choose a safer current that restores more health or a fractured passage with a tougher fight and a stronger card pool.",
    helpKeysTitle: "Quick controls",
    helpKeysBody: "Press 1–5 to select a card, arrow keys to choose a foe, Enter to play, E to end the turn, R to reweave, and Esc to open settings.",
    startHint: "No account. No downloads. Your chart stays on this device.",
    chapter: "Drowned Observatory",
    route: "Expedition route",
    step: "BEAT {n} OF 3",
    seed: "Seed {seed}",
    turn: "Turn {turn}",
    health: "Hull",
    guard: "Guard",
    energy: "Current",
    drawPile: "Draw pile",
    discardPile: "Discard",
    deck: "Chart deck",
    incoming: "Incoming",
    damage: "{n} damage",
    danger: "DANGER",
    turnTitle: "Your turn",
    enemyTurn: "Their turn",
    enemiesActing: "The archive stirs",
    resolving: "Resolving…",
    chartkeeper: "Chartkeeper",
    battlefield: "Battlefield",
    hand: "Your hand",
    shapeResonance: "Weave two sigils",
    sigilDetails: "Sigils & Resonance",
    touchCardHint: "Tap a card to read, then cast",
    touchConfirmHint: "Tap this card again to cast",
    touchTargetHint: "Tap a foe, or tap this card again to cast",
    rotateTitle: "A wider horizon",
    rotateDescription: "Turn your phone sideways to play Triseal.",
    sceneLabel: "BENEATH THE OBSERVATORY",
    actionInterrupted: "That action was interrupted. Your previous turn state has been restored.",
    logBlocked: "{name} blocks {n} damage.",
    turnHint: "Read the intent. Braid your cards. Choose your moment.",
    wakeTitle: "The Wake",
    wakeReady: "Wake woven",
    wakeProgress: "Distinct currents",
    sigilTide: "Tide",
    sigilEmber: "Ember",
    sigilGlass: "Glass",
    intentAttack: "Strike · {n}",
    intentBrace: "Brace · {n}",
    intentCharge: "Gather · +{n}",
    intentNoMove: "No intent",
    chooseFoe: "Choose a foe",
    clickCardHint: "Play a card from your hand",
    targetHint: "Choose a foe to target",
    play: "Play",
    endTurn: "End turn",
    reweave: "Reweave",
    reweaveAvailable: "Replace this hand once this expedition.",
    reweaveUsed: "Reweave spent",
    reweaveEmpty: "There are no cards left in your hand.",
    cardNotReady: "Not enough current for that card.",
    cardHandLimit: "Your hand is full.",
    deckPeek: "View deck",
    deckTitle: "Your chart deck",
    deckSummary: "{draw} to draw · {discard} discarded · {hand} in hand",
    noCards: "No cards in this pile.",
    battleLog: "Current log",
    logTurn: "Turn {n} begins. Three current available.",
    logWake: "The three currents answer together. Wake!",
    logSteam: "Steam veils the field. Foe attacks lose 2 damage this turn.",
    logPrism: "Prism is charged. Your next attack card gains 3 damage per foe it hits.",
    logPrismStrike: "Prism adds {n} damage to each foe struck.",
    logMirror: "Mirror turns the currents into 5 guard.",
    logDamage: "{name} takes {n} damage.",
    logGuard: "You gain {n} guard.",
    logDraw: "You draw {n}.",
    logEnemyAttack: "{name} strikes for {n}.",
    logEnemyBrace: "{name} braces for {n}.",
    logEnemyCharge: "{name} gathers {n} power.",
    logEnemyDown: "{name} falls quiet.",
    logReweave: "The hand is rewoven; this expedition's chance is spent.",
    logTide: "The passage restores {n} hull.",
    logTarget: "Choose a foe for {card}.",
    rewardTitle: "A strand worth keeping",
    rewardDescription: "Choose one card for your chart deck, or leave the archive lighter.",
    skipReward: "Skip this strand",
    routeTitle: "Where will the thread lead?",
    routeDescription: "Both passages return to the horizon. One gives you time to mend; the other pays for a risk.",
    quietTitle: "The Sheltered Current",
    quietDescription: "Recover 8 hull. Face one steady reef sentinel.",
    riftTitle: "The Fractured Passage",
    riftDescription: "Recover 2 hull. Face a pair of volatile foes; the card pool runs deeper.",
    choosePassage: "Chart this passage",
    bossTitle: "The Missing Horizon",
    bossDescription: "A chart without an edge has learned to bite.",
    titleShoal: "The Chalk Shoal",
    titleQuiet: "The Sheltered Current",
    titleRift: "The Fractured Passage",
    titleBoss: "The Missing Horizon",
    enemyDriftling: "Driftling",
    enemyBrineback: "Brineback",
    enemyMirrorfin: "Mirrorfin",
    enemyInkling: "Inkling",
    enemyBellwether: "Bellwether",
    enemyHorizon: "Horizon Without Edge",
    enemyKind: "ARCHIVE FAUNA",
    allFoes: "All foes",
    pausedTitle: "Chart paused",
    resume: "Back to the current",
    saveAndLeave: "Save & return to title",
    leaveTitle: "Return to title",
    leaveBody: "Your expedition is saved on this device.",
    runWon: "The horizon returns",
    runLost: "The chart goes dark",
    runWonBody: "You stitched a path through the observatory. The sea remembers your route.",
    runLostBody: "The currents pull apart. Your next chart will start with the same hard-earned knowledge.",
    runStats: "Expedition notes",
    turnsTaken: "Turns charted",
    cardsInDeck: "Cards collected",
    bestSeed: "Run seed",
    newRun: "Chart again",
    home: "Return to title",
    log: "Log",
    currentFoe: "CURRENT FOE",
    targetSelected: "TARGET SELECTED",
    targetFoe: "Select target",
    cardCost: "COST",
    chooseCard: "Choose this card",
    noReward: "No card added.",
    routeRisk: "RISK",
    routeRest: "RECOVERY",
    hullFull: "Hull {current} / {max}",
    footer: "A small original game about the shape of a good turn.",
    wakeHint: "Your second different sigil picks a reaction below. The third unleashes a Wake.",
    wakeEffect: "All foes −4 · Guard +4 · Draw 1",
    resonanceSteamTitle: "Steam",
    resonanceSteamEffect: "Foe attacks −2 this turn",
    resonancePrismTitle: "Prism",
    resonancePrismEffect: "Next attack card +3 damage per foe",
    resonancePrismSpent: "Prism bonus spent",
    prismCardPreview: "Prism: +{n} damage to every foe this card hits.",
    resonanceSteamOption: "Steam · attacks −2",
    resonancePrismOption: "Prism · next hit +3",
    resonanceMirrorOption: "Mirror · guard +5",
    resonanceMirrorTitle: "Mirror",
    resonanceMirrorEffect: "5 guard gained",
    resonanceWakeHint: "Add the final sigil to unleash the Wake.",
    effectDamage: "Deal {n} damage",
    effectBlock: "Gain {n} guard",
    effectDraw: "Draw {n}",
    effectMixed: "Deal {damage} damage · Gain {guard} guard",
    effectMixedDraw: "Deal {damage} · Gain {guard} guard · Draw {draw}",
    effectAll: "Deal {n} to all foes",
    effectAllBlock: "Deal {damage} to all foes · Gain {guard} guard",
    effectBlockDraw: "Gain {guard} guard · Draw {draw}",
    value: "VALUE",
    skip: "Skip",
    overwriteConfirm: "Start a new expedition and replace the saved one?",
    wakeCounter: "{n} of 3 distinct currents",
  },
  zh: {
    appTitle: "三印唤潮",
    subtitle: "绘出流动的海，不让任何一缕线索遗落。",
    homeEyebrow: "深海之下的卡牌肉鸽",
    homeDescription: "沉没观测站失去了海平线。读懂潮流，织出一条路，把一点光带回档案馆。",
    begin: "开启航图",
    continueRun: "继续远征",
    seedLabel: "本局种子",
    seedPlaceholder: "留空则随机生成",
    seedHint: "分享种子即可重走同一条路线。",
    welcome: "三种潮流，唤起一道浪。",
    welcomeDescription: "前两种不同印记决定共鸣效果，再打出第三种即可唤起「唤潮」。",
    howTo: "玩法说明",
    language: "English",
    sound: "音效",
    settings: "设置",
    settingsTitle: "航图设置",
    close: "关闭",
    soundToggle: "音效与音乐",
    reducedMotion: "减少动态效果",
    volume: "总音量",
    musicToggle: "环境配乐",
    on: "开启",
    off: "关闭",
    helpTitle: "三种潮流编成一张航图",
    helpWakeTitle: "编织共鸣",
    helpWakeBody: "本回合前两种不同印记决定共鸣：潮汐+余烬形成「蒸雾」（敌人攻击伤害−2）；余烬+琉璃形成「棱光」（下一张攻击牌每命中一名敌人，额外造成3点伤害）；琉璃+潮汐形成「映盾」（获得5点格挡）。打出第三种印记即可唤潮：对所有敌人造成4点伤害、获得4点格挡并抽1张牌。重复印记不会改变组合。",
    helpTurnTitle: "读懂潮水",
    helpTurnBody: "每个敌人都会提前展示下一步行动。你有3点能量，可按任意顺序打牌，然后结束回合。格挡只持续到回合结束。",
    helpReweaveTitle: "每次远征重织一次",
    helpReweaveBody: "每次远征可以把当前手牌全部替换为同样数量的新牌。可在困难回合结束前使用。",
    helpRouteTitle: "选择一条水道",
    helpRouteBody: "第一场战斗后，选择更安全、恢复较多生命的水道，或选择敌人更强、卡牌奖励池更丰富的裂隙水道。",
    helpKeysTitle: "快捷操作",
    helpKeysBody: "按1–5选择卡牌，方向键选择敌人，Enter出牌，E结束回合，R重织手牌，Esc打开设置。",
    startHint: "无需账号或下载。你的航图只保存在此设备。",
    chapter: "沉没观测站",
    route: "远征路线",
    step: "第 {n} 拍，共 3 拍",
    seed: "种子 {seed}",
    turn: "第 {turn} 回合",
    health: "船体",
    guard: "格挡",
    energy: "潮流",
    drawPile: "抽牌堆",
    discardPile: "弃牌堆",
    deck: "航图牌组",
    incoming: "即将承受",
    damage: "{n} 点伤害",
    danger: "危险",
    turnTitle: "你的回合",
    enemyTurn: "敌方回合",
    enemiesActing: "档案中的生灵开始行动",
    resolving: "结算中…",
    chartkeeper: "绘潮人",
    battlefield: "战场",
    hand: "你的手牌",
    shapeResonance: "两印交织，选择共鸣",
    sigilDetails: "印记与共鸣",
    touchCardHint: "点牌查看，确认后施放",
    touchConfirmHint: "再点此牌，确认施放",
    touchTargetHint: "点选敌人，或再次点牌施放",
    rotateTitle: "转过手机，展开战场",
    rotateDescription: "请将手机横过来，继续三印唤潮。",
    sceneLabel: "观测站的深处",
    actionInterrupted: "动作中断，已恢复到这次行动前的状态。",
    logBlocked: "{name}格挡了{n}点伤害。",
    turnHint: "读懂意图，编织手牌，等待出击时机。",
    wakeTitle: "唤潮",
    wakeReady: "潮流已织成",
    wakeProgress: "不同印记",
    sigilTide: "潮汐",
    sigilEmber: "余烬",
    sigilGlass: "琉璃",
    intentAttack: "攻击 · {n}",
    intentBrace: "蓄甲 · {n}",
    intentCharge: "蓄势 · +{n}",
    intentNoMove: "暂无动作",
    chooseFoe: "选择目标",
    clickCardHint: "从手牌中打出一张卡",
    targetHint: "请选择攻击目标",
    play: "打出",
    endTurn: "结束回合",
    reweave: "重织手牌",
    reweaveAvailable: "本次远征可替换当前手牌一次。",
    reweaveUsed: "重织次数已用",
    reweaveEmpty: "手牌为空，无法重织。",
    cardNotReady: "潮流不足，无法打出此牌。",
    cardHandLimit: "手牌已满。",
    deckPeek: "查看牌组",
    deckTitle: "你的航图牌组",
    deckSummary: "抽牌堆 {draw} 张 · 弃牌堆 {discard} 张 · 手牌 {hand} 张",
    noCards: "此牌堆为空。",
    battleLog: "潮流记录",
    logTurn: "第 {n} 回合开始，潮流恢复。",
    logWake: "三种潮流同时回应。唤潮！",
    logSteam: "蒸雾笼罩战场，本回合敌人的攻击伤害降低2点。",
    logPrism: "棱光蓄势：你的下一张攻击牌每命中一名敌人，额外造成3点伤害。",
    logPrismStrike: "棱光为每名被击中的敌人额外造成{n}点伤害。",
    logMirror: "映盾折成5点格挡。",
    logDamage: "{name}受到{n}点伤害。",
    logGuard: "获得{n}点格挡。",
    logDraw: "抽到{n}张牌。",
    logEnemyAttack: "{name}发动攻击，造成{n}点伤害。",
    logEnemyBrace: "{name}蓄起{n}点护甲。",
    logEnemyCharge: "{name}蓄势，攻击力提高{n}。",
    logEnemyDown: "{name}沉寂了。",
    logReweave: "手牌已重织，本次远征的机会已用完。",
    logTide: "这条水道修复了{n}点船体。",
    logTarget: "为「{card}」选择目标。",
    rewardTitle: "留下这一缕线索",
    rewardDescription: "从航图牌组中选择一张新牌，也可以轻装离开档案馆。",
    skipReward: "跳过奖励",
    routeTitle: "这缕丝线通往何方？",
    routeDescription: "两条水道都会回到海平线。一条让你休整，另一条以风险换取更好的牌。",
    quietTitle: "避风潮道",
    quietDescription: "恢复8点船体。迎战一只沉稳的礁石守卫。",
    riftTitle: "碎裂水道",
    riftDescription: "恢复2点船体。迎战两只变幻莫测的敌人，卡池也更丰富。",
    choosePassage: "选择这条水道",
    bossTitle: "失落的海平线",
    bossDescription: "没有边界的航图，学会了反咬一口。",
    titleShoal: "粉笔浅滩",
    titleQuiet: "避风潮道",
    titleRift: "碎裂水道",
    titleBoss: "失落的海平线",
    enemyDriftling: "漂流灵",
    enemyBrineback: "盐甲兽",
    enemyMirrorfin: "镜鳍鱼",
    enemyInkling: "墨团",
    enemyBellwether: "潮钟使",
    enemyHorizon: "无边海平线",
    enemyKind: "档案馆海兽",
    allFoes: "所有敌人",
    pausedTitle: "航图已暂停",
    resume: "返回潮流",
    saveAndLeave: "保存并返回标题",
    leaveTitle: "返回标题",
    leaveBody: "远征进度已保存在此设备。",
    runWon: "海平线重现",
    runLost: "航图暗了下来",
    runWonBody: "你织出一条穿过观测站的路。大海记得你走过的路线。",
    runLostBody: "潮流散开了。下一张航图会带上这次远征的经验。",
    runStats: "远征记录",
    turnsTaken: "已航行回合",
    cardsInDeck: "收集卡牌",
    bestSeed: "本局种子",
    newRun: "重新绘制",
    home: "返回标题",
    log: "记录",
    currentFoe: "当前敌人",
    targetSelected: "已选目标",
    targetFoe: "选择目标",
    cardCost: "消耗",
    chooseCard: "收下这张牌",
    noReward: "没有收下新牌。",
    routeRisk: "风险",
    routeRest: "恢复",
    hullFull: "船体 {current} / {max}",
    footer: "关于如何打好一个回合的原创小品。",
    wakeHint: "第二种不同印记决定下方共鸣；第三种即可唤潮。",
    wakeEffect: "所有敌人 −4 · 格挡 +4 · 抽牌 1",
    resonanceSteamTitle: "蒸雾",
    resonanceSteamEffect: "本回合敌人攻击 −2",
    resonancePrismTitle: "棱光",
    resonancePrismEffect: "下一张攻击牌每命中一名敌人 +3 伤害",
    resonancePrismSpent: "棱光加成已用",
    prismCardPreview: "棱光：此牌每命中一名敌人，额外造成{n}点伤害。",
    resonanceSteamOption: "蒸雾 · 攻击 −2",
    resonancePrismOption: "棱光 · 下次命中 +3",
    resonanceMirrorOption: "映盾 · 格挡 +5",
    resonanceMirrorTitle: "映盾",
    resonanceMirrorEffect: "已获得 5 点格挡",
    resonanceWakeHint: "打出最后一种印记即可唤潮。",
    effectDamage: "造成 {n} 点伤害",
    effectBlock: "获得 {n} 点格挡",
    effectDraw: "抽 {n} 张牌",
    effectMixed: "造成 {damage} 点伤害 · 获得 {guard} 点格挡",
    effectMixedDraw: "造成 {damage} 点伤害 · 格挡 +{guard} · 抽牌 {draw}",
    effectAll: "对所有敌人造成 {n} 点伤害",
    effectAllBlock: "所有敌人受到 {damage} 点伤害 · 格挡 +{guard}",
    effectBlockDraw: "格挡 +{guard} · 抽牌 {draw}",
    value: "数值",
    skip: "跳过",
    overwriteConfirm: "重新开始并覆盖当前保存的远征进度吗？",
    wakeCounter: "已连接 {n} / 3 种不同潮流",
  },
};

export const SIGILS = ["tide", "ember", "glass"];

export const SIGIL_NAME = {
  tide: { en: "sigilTide", zh: "sigilTide" },
  ember: { en: "sigilEmber", zh: "sigilEmber" },
  glass: { en: "sigilGlass", zh: "sigilGlass" },
};

export const SIGIL_GLYPH = { tide: "≈", ember: "✳", glass: "◇" };

export const CARDS = {
  needle: {
    sigil: "ember", cost: 1, type: "damage", value: 6, target: true, starter: true,
    glyph: "↗", tone: "ember",
    en: { name: "Thread Needle", text: "Deal 6 damage." },
    zh: { name: "引线针", text: "造成6点伤害。" },
  },
  brace: {
    sigil: "tide", cost: 1, type: "block", value: 5, starter: true,
    glyph: "⌒", tone: "tide",
    en: { name: "Fold the Current", text: "Gain 5 guard." },
    zh: { name: "折叠潮流", text: "获得5点格挡。" },
  },
  glassline: {
    sigil: "glass", cost: 0, type: "draw", value: 1, starter: true,
    glyph: "⌁", tone: "glass",
    en: { name: "Read the Glass", text: "Draw 1 card." },
    zh: { name: "读懂琉璃", text: "抽1张牌。" },
  },
  undertow: {
    sigil: "glass", cost: 1, type: "damageBlock", damage: 4, block: 3, target: true, starter: true,
    glyph: "⌁", tone: "glass",
    en: { name: "Undertow", text: "Deal 4 damage. Gain 3 guard." },
    zh: { name: "暗流", text: "造成4点伤害，获得3点格挡。" },
  },
  cinder: {
    sigil: "ember", cost: 2, type: "damage", value: 10, target: true,
    glyph: "✴", tone: "ember",
    en: { name: "Cinder Pin", text: "Deal 10 damage." },
    zh: { name: "余烬钉", text: "造成10点伤害。" },
  },
  mooring: {
    sigil: "tide", cost: 2, type: "block", value: 9,
    glyph: "⚓", tone: "tide",
    en: { name: "Soft Mooring", text: "Gain 9 guard." },
    zh: { name: "柔锚", text: "获得9点格挡。" },
  },
  prism: {
    sigil: "glass", cost: 1, type: "blockDraw", block: 2, draw: 1,
    glyph: "◇", tone: "glass",
    en: { name: "Prism Draft", text: "Draw 1 card. Gain 2 guard." },
    zh: { name: "棱镜气流", text: "抽1张牌，获得2点格挡。" },
  },
  crosscut: {
    sigil: "ember", cost: 1, type: "allDamage", value: 4,
    glyph: "✳", tone: "ember",
    en: { name: "Crosscut", text: "Deal 4 damage to all foes." },
    zh: { name: "交叉切线", text: "对所有敌人造成4点伤害。" },
  },
  shoreless: {
    sigil: "ember", cost: 2, type: "damageDraw", damage: 8, draw: 1, target: true,
    glyph: "↗", tone: "ember",
    en: { name: "No Shore", text: "Deal 8 damage. Draw 1 card." },
    zh: { name: "无岸之处", text: "造成8点伤害，抽1张牌。" },
  },
  shoalwall: {
    sigil: "tide", cost: 1, type: "blockDraw", block: 4, draw: 1,
    glyph: "⌒", tone: "tide",
    en: { name: "Shoal Wall", text: "Gain 4 guard. Draw 1 card." },
    zh: { name: "浅滩屏障", text: "获得4点格挡，抽1张牌。" },
  },
  wavebreak: {
    sigil: "glass", cost: 2, type: "allDamageBlock", damage: 5, block: 5,
    glyph: "⌁", tone: "glass",
    en: { name: "Wavebreak", text: "Deal 5 to all foes. Gain 5 guard." },
    zh: { name: "碎浪", text: "对所有敌人造成5点伤害，获得5点格挡。" },
  },
};

export const ENEMIES = {
  driftling: {
    hp: 18, kind: "orb",
    pattern: [{ type: "attack", value: 5 }, { type: "attack", value: 5 }, { type: "brace", value: 4 }],
  },
  brineback: {
    hp: 24, kind: "shell",
    pattern: [{ type: "brace", value: 5 }, { type: "attack", value: 7 }, { type: "attack", value: 4 }],
  },
  mirrorfin: {
    hp: 31, kind: "fin",
    pattern: [{ type: "attack", value: 6 }, { type: "brace", value: 5 }, { type: "attack", value: 8 }],
  },
  inkling: {
    hp: 25, kind: "ink",
    pattern: [{ type: "attack", value: 6 }, { type: "charge", value: 2 }, { type: "attack", value: 8 }],
  },
  bellwether: {
    hp: 28, kind: "bell",
    pattern: [{ type: "charge", value: 2 }, { type: "attack", value: 7 }, { type: "brace", value: 5 }],
  },
  horizon: {
    hp: 62, kind: "boss",
    pattern: [{ type: "attack", value: 7 }, { type: "charge", value: 2 }, { type: "attack", value: 11 }, { type: "brace", value: 8 }],
  },
};

export const ENCOUNTERS = {
  shoal: { title: "titleShoal", enemies: ["driftling", "brineback"] },
  quiet: { title: "titleQuiet", enemies: ["mirrorfin"] },
  rift: { title: "titleRift", enemies: ["inkling", "bellwether"] },
  boss: { title: "titleBoss", enemies: ["horizon"] },
};

export const REWARD_POOLS = {
  standard: ["cinder", "mooring", "prism", "crosscut", "shoreless", "shoalwall"],
  deep: ["cinder", "mooring", "prism", "crosscut", "shoreless", "shoalwall", "wavebreak", "undertow"],
};
